name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install poetry
          make PyYAML
          make dependencies
          make install
      - name: Run linter and pytest
        run: |
          make lint
          poetry run pytest -vv tests
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v8.0.0
        if: github.ref_name == 'main'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.1beea7c67613e1c943542cc19b58cc4ff0c754bebf49585c31f7629dd827ecf5 }}
        with:
          coverageCommand: pytest --cov=gendiff tests/
          debug: true
