name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install poetry
          make dependencies
          make install
      - name: Run linter and pytest
        run: |
          make lint
          poetry run pytest -vv tests
      - name: Download codeclimate reporter
        run: wget -O cc-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 && chmod +x cc-reporter
      - name: Prepare code coverage
        run: ./cc-reporter before-build
      - name: Format code coverage
        run: ./cc-reporter format-coverage c.out -t gocov -p $(basename $PWD)
      - name: Upload code coverage
        env:
          CC_TEST_REPORTER_ID: ...
        run: ./cc-reporter after-build -t gocov -p $(basename $PWD)
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        if: github.ref_name == 'main'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: pytest --cov=gendiff tests/
          debug: true
